FROM stagex/pallet-rust@sha256:9c38bf1066dd9ad1b6a6b584974dd798c2bf798985bf82e58024fbe0515592ca AS pallet-rust
FROM stagex/core-busybox@sha256:637b1e0d9866807fac94c22d6dc4b2e1f45c8a5ca1113c88172e0324a30c7283 AS busybox
FROM stagex/core-musl@sha256:d9af23284cca2e1002cd53159ada469dfe6d6791814e72d6163c7de18d4ae701 AS musl
FROM stagex/core-gcc@sha256:964ffd3793c5a38ca581e9faefd19918c259f1611c4cbf5dc8be612e3a8b72f5 AS gcc
FROM stagex/core-libunwind@sha256:eb66122d8fc543f5e2f335bb1616f8c3a471604383e2c0a9df4a8e278505d3bc AS libunwind
FROM stagex/core-openssl@sha256:d6487f0cb15f4ee02b420c717cb9abd85d73043c0bb3a2c6ce07688b23c1df07 AS openssl
FROM stagex/core-zlib@sha256:06f5168e20d85d1eb1d19836cdf96addc069769b40f8f0f4a7a70b2f49fc18f8 AS zlib
FROM stagex/core-ca-certificates@sha256:d135f1189e9b232eb7316626bf7858534c5540b2fc53dced80a4c9a95f26493e AS ca-certificates
FROM stagex/core-libzstd@sha256:5382c221194b6d0690eb65ccca01c720a6bd39f92e610dbc0e99ba43f38f3094 AS libzstd
FROM stagex/user-cpio@sha256:9c8bf39001eca8a71d5617b46f8c9b4f7426db41a052f198d73400de6f8a16df AS cpio
FROM stagex/user-socat@sha256:4d1b7a403eba65087a3f69200d2644d01b63f0ea81ef171cedc17de490c8c9a0 AS socat
FROM stagex/user-eif_build@sha256:935032172a23772ea1a35c6334aa98aa7b0c46f9e34a040347c7b2a73496ef8a AS eif-build
FROM stagex/user-linux-nitro@sha256:aa1006d91a7265b33b86160031daad2fdf54ec2663ed5ccbd312567cc9beff2c AS linux-nitro
FROM stagex/user-nit@sha256:60b6eef4534ea6ea78d9f29e4c7feb27407b615424f20ad8943d807191688be7 AS nit
FROM stagex/core-git@sha256:6b3e0055f6aeaa8465f207a871db2c63a939cd7406113e9d769ff3b37239f3d0 AS git
FROM stagex/core-curl@sha256:bc8bab43d96a9167fbb85022ea773644a45ef335e7a9b747f203078973fa988e AS curl
{steve_builder_stage}
FROM pallet-rust AS enclave-builder

ENV SOURCE_DATE_EPOCH=1
ENV CARGO_HOME=/usr/local/cargo
ENV RUSTFLAGS="-C codegen-units=1 -C target-feature=+crt-static -C link-arg=-Wl,--build-id=none"
ENV TARGET_ARCH="x86_64-unknown-linux-musl"

WORKDIR /build-enclave

COPY enclave/ /build-enclave/

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    cargo fetch --locked --target $TARGET_ARCH

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/build-enclave/target \
    cargo build --release --locked --target ${{TARGET_ARCH}} -p attestation-service \
      && install -D -m 0755 /build-enclave/target/${{TARGET_ARCH}}/release/attestation-service /binaries/attestation-service

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,target=/build-enclave/target \
    cargo build --release --locked --target ${{TARGET_ARCH}} -p init \
      && install -D -m 0755 /build-enclave/target/${{TARGET_ARCH}}/release/init /binaries/init

FROM busybox AS eif-builder

COPY --from=musl . /
COPY --from=gcc . /
COPY --from=libunwind . /
COPY --from=openssl . /
COPY --from=zlib . /
COPY --from=ca-certificates . /
COPY --from=libzstd . /
COPY --from=cpio . /
COPY --from=socat . /
COPY --from=eif-build . /
COPY --from=nit . /

WORKDIR /build

COPY --from=enclave-builder /binaries/ /build/binaries/
{steve_copy}

COPY --from=linux-nitro /bzImage /build/kernel/bzImage
COPY --from=linux-nitro /linux.config /build/kernel/linux.config

COPY app/ /build/app/

COPY run.sh /build/run.sh

COPY enclave/rootfs/udhcpc-script.sh /build/udhcpc-script.sh

COPY manifest.json /build/manifest.json

RUN mkdir -p /build/initramfs/bin && \
    mkdir -p /build/initramfs/lib && \
    mkdir -p /build/initramfs/etc/ssl/certs

RUN cp /bin/init /build/initramfs/init && \
    chmod +x /build/initramfs/init

RUN cp /build/run.sh /build/initramfs/run.sh && \
    chmod +x /build/initramfs/run.sh

RUN cp /build/udhcpc-script.sh /build/initramfs/bin/udhcpc-script && \
    chmod +x /build/initramfs/bin/udhcpc-script

RUN cp /build/binaries/attestation-service /build/initramfs/attestation-service && \
    chmod +x /build/initramfs/attestation-service

{steve_install}

RUN if [ -f /build/manifest.json ]; then \
        cp /build/manifest.json /build/initramfs/manifest.json; \
    fi

RUN if [ -f /bin/busybox ]; then \
        cp /bin/busybox /build/initramfs/bin/busybox && \
        cd /build/initramfs/bin && \
        ln -s busybox sh && \
        ln -s busybox sleep && \
        ln -s busybox find && \
        ln -s busybox cat && \
        ln -s busybox ls && \
        ln -s busybox mkdir && \
        ln -s busybox mount && \
        ln -s busybox chmod && \
        ln -s busybox ip && \
        ln -s busybox grep && \
        ln -s busybox udhcpc; \
    fi

RUN if [ -f /usr/bin/socat ]; then \
        cp /usr/bin/socat /build/initramfs/bin/socat && \
        chmod +x /build/initramfs/bin/socat; \
    elif [ -f /bin/socat ]; then \
        cp /bin/socat /build/initramfs/bin/socat && \
        chmod +x /build/initramfs/bin/socat; \
    fi

RUN if [ -f /lib/ld-musl-x86_64.so.1 ]; then \
        cp /lib/ld-musl-x86_64.so.1 /build/initramfs/lib/ld-musl-x86_64.so.1; \
    fi

RUN if [ -f /etc/ssl/certs/ca-certificates.crt ]; then \
        cp /etc/ssl/certs/ca-certificates.crt /build/initramfs/etc/ssl/certs/ca-certificates.crt; \
    fi

# Copy user app files to initramfs root to preserve original paths
RUN cp -r /build/app/* /build/initramfs/ 2>/dev/null || true

RUN find /build/initramfs -exec touch -hcd "@0" "{{}}" +

RUN cd /build/initramfs && \
    find . -print0 | sort -z | cpio --null --create --format=newc --reproducible | gzip --best > /build/rootfs.cpio.gz

RUN eif_build \
    --kernel /build/kernel/bzImage \
    --kernel_config /build/kernel/linux.config \
    --ramdisk /build/rootfs.cpio.gz \
    --output /build/enclave.eif \
    --pcrs_output /build/enclave.pcrs \
    --cmdline "reboot=k panic=1 pci=off nomodules console=ttyS0 i8042.noaux i8042.nomux i8042.nopnp i8042.dumbkbd nit.target=/run.sh"

FROM scratch AS output
COPY --from=eif-builder /build/enclave.eif /enclave.eif
COPY --from=eif-builder /build/enclave.pcrs /enclave.pcrs
COPY --from=eif-builder /build/rootfs.cpio.gz /rootfs.cpio.gz
