# Caution Build Configuration
# Procfile docs: https://docs.caution.co/reference/procfile/

# Run command for the application
run: /usr/local/bin/hello

# Application source (for reproducing in order to verify)
# https://docs.caution.co/concepts/verifiability/
app_sources: git@codeberg.org:caution/demo-hello-world-enclave.git

# App port
ports: 8083 
