// SPDX-FileCopyrightText: 2026 Caution SEZC
// SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Commercial

//! # Drift Detector
//!
//! This crate detects drift between the expected state stored in the database
//! and the actual state of AWS resources.
//!
//! ## Overview
//!
//! The drift detector works by:
//! 1. Reading expected resource state from the database (`db` module)
//! 2. Querying actual AWS resource state (`aws` module)
//! 3. Comparing the two states and reporting differences
//!
//! ## Module Structure
//!
//! - `db`: Database access layer for reading expected state
//! - `aws`: AWS API client for querying actual state
//! - `drift`: Core drift detection logic comparing db vs aws state
//!
//! ## Error Handling
//!
//! Each fallible module exposes a strict dterror error enum (derived with
//! `thiserror::Error` and `dterror::CtxError`). Every variant is a named struct
//! variant carrying the call-site location, and every failure mode that has an
//! underlying error carries it as an erased `#[source]`. The `{Error}Ctx`
//! context mirrors generated by the derive are internal plumbing and carry no
//! per-item documentation.
//!
//! - [`db::DbError`]: database query failures, carrying the organization and/or
//!   resource identifiers involved
//! - [`aws::AwsError`]: AWS API call failures (instance listing carries the
//!   queried region; region discovery failures are surfaced separately)

// The `CtxError` derive generates a `{Error}Ctx` mirror type per error enum
// whose generated items cannot carry per-item documentation, so the lint cannot
// be enabled crate-wide.
#![allow(
    missing_docs,
    reason = "generated {Error}Ctx mirrors carry no per-item docs"
)]
#![warn(missing_debug_implementations)]
// The instrumented async entry points wrap sqlx's compile-time query
// type-checking in deeply nested generated futures; the default recursion limit
// is too low to compute those layouts.
#![recursion_limit = "256"]

pub mod aws;
pub mod db;
pub mod drift;

pub use aws::AwsError;
pub use db::DbError;
