# SPDX-FileCopyrightText: 2026 Caution SEZC
# SPDX-License-Identifier: AGPL-3.0-only OR LicenseRef-Caution-Commercial

FROM stagex/pallet-rust@sha256:9c38bf1066dd9ad1b6a6b584974dd798c2bf798985bf82e58024fbe0515592ca AS rust
FROM stagex/core-ca-certificates@sha256:d135f1189e9b232eb7316626bf7858534c5540b2fc53dced80a4c9a95f26493e AS ca-certificates

FROM rust AS tap-framer-builder
COPY --from=ca-certificates . /
ENV SOURCE_DATE_EPOCH=1
ENV CARGO_HOME=/usr/local/cargo
ENV RUSTFLAGS="-C codegen-units=1 -C target-feature=+crt-static -C link-arg=-Wl,--build-id=none"
ENV TARGET_ARCH="x86_64-unknown-linux-musl"
WORKDIR /build-tap-framer
COPY src/tap-framer/Cargo.toml src/tap-framer/Cargo.lock /build-tap-framer/
COPY src/tap-framer/src/ /build-tap-framer/src/
RUN cargo fetch --locked --target $TARGET_ARCH
RUN --network=none cargo build --release --frozen --target ${TARGET_ARCH} && \
    install -D -m 0755 target/${TARGET_ARCH}/release/tap-framer /binaries/tap-framer && \
    cd /binaries && sha256sum tap-framer > tap-framer.sha256

FROM scratch AS tap-framer-export
COPY --from=tap-framer-builder /binaries/tap-framer /tap-framer
COPY --from=tap-framer-builder /binaries/tap-framer.sha256 /tap-framer.sha256
