FROM stagex/pallet-rust@sha256:4062550919db682ebaeea07661551b5b89b3921e3f3a2b0bc665ddea7f6af1ca AS pallet-rust
FROM stagex/core-gcc@sha256:964ffd3793c5a38ca581e9faefd19918c259f1611c4cbf5dc8be612e3a8b72f5 AS gcc
FROM stagex/core-musl@sha256:d9af23284cca2e1002cd53159ada469dfe6d6791814e72d6163c7de18d4ae701 AS musl
FROM stagex/core-libunwind@sha256:eb66122d8fc543f5e2f335bb1616f8c3a471604383e2c0a9df4a8e278505d3bc AS libunwind
FROM stagex/core-ca-certificates@sha256:d135f1189e9b232eb7316626bf7858534c5540b2fc53dced80a4c9a95f26493e AS ca-certificates
FROM stagex/core-user-runtime@sha256:055ae534e1e01259449fb4e0226f035a7474674c7371a136298e8bdac65d90bb AS user-runtime
FROM stagex/user-pcsc-lite@sha256:2e0bb1cbeb9dd97be4e0594bd712dc138ee2710668281d3faa1a18d99a50979d AS pcsc-lite
FROM stagex/user-nettle@sha256:3b883ec8fb6781acff2517e7485d7e8f79f147f8fa2b3b644cb96da495af52e7 AS nettle
FROM stagex/core-gmp@sha256:35f1f6f285efd438e7d985dc0538b7a5ca1a228e69f50d39de2bcafe830b4beb AS gmp

FROM pallet-rust AS builder

COPY --from=pcsc-lite . /
COPY --from=nettle . /
COPY --from=gmp . /

ENV SOURCE_DATE_EPOCH=1
ENV CARGO_HOME=/usr/local/cargo

WORKDIR /build

COPY . .

ENV RUST_BACKTRACE=1
ENV RUSTFLAGS="-C codegen-units=1"
ENV RUSTFLAGS="${RUSTFLAGS} -C target-feature=+crt-static"
ENV RUSTFLAGS="${RUSTFLAGS} -C link-arg=-Wl,--build-id=none"
ENV TARGET_ARCH="x86_64-unknown-linux-musl"
ENV NETTLE_STATIC=1

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    find /usr/local/cargo/registry -name '.cargo-ok' -delete 2>/dev/null || true && \
    cargo fetch --locked --target $TARGET_ARCH

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,id=metering-target,target=/build/target \
    --network=none \
    cargo build --release --frozen \
      --bin metering \
      --target ${TARGET_ARCH} \
      && install -D -m 0755 /build/target/${TARGET_ARCH}/release/metering /usr/local/bin/metering

FROM user-runtime AS runtime

COPY --from=gcc /usr/lib/libgcc_s.so.1 /usr/lib/
COPY --from=gcc /usr/lib/libstdc++.so.6 /usr/lib/
COPY --from=musl /lib/ld-musl-x86_64.so.1 /lib/
COPY --from=libunwind /lib/libunwind.so.8 /lib/
COPY --from=ca-certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/local/bin/metering /usr/local/bin/metering

WORKDIR /app

ENV RUST_LOG=info

EXPOSE 8083

ENTRYPOINT ["metering"]
