FROM stagex/pallet-rust@sha256:abe9b95c93a5afa271f69fcd5eb18c8cd405fe5df6491a63c9418e3a170573dc AS pallet-rust
FROM stagex/core-gcc@sha256:7bccb77b1b97b3b84ac6db30b6dd90107682817b67e55df10abda6bbbf0a0d80 AS gcc
FROM stagex/core-musl@sha256:42fd2ed18ac4d6336f08f1b6345e0bb7bc5570450a40e7255b6da79868bd2d6b AS musl
FROM stagex/core-libunwind@sha256:08cd9e229ef1b4f547c25436d06a2f893f252fc1c1d8b86affbaa91b0be05cef AS libunwind
FROM stagex/core-ca-certificates@sha256:8390dff73a4502614411e2b2ecb4e4e33b6cc10dc26cf2c6a46e5df71f4c4b03 AS ca-certificates
FROM stagex/core-user-runtime@sha256:1694accf42714684f8ebefed165dd202efb474d53cafbd47b63f93b47c999cad AS user-runtime
FROM stagex/user-pcsc-lite@sha256:58e5846a6c0aa394d55f00a8bf743aab41e024449c31d199af868f012accc326 AS pcsc-lite
FROM stagex/user-nettle@sha256:110504b49f494b06121d1816eaa18aae2b772761e6748229d5bff1260a0f9860 AS nettle
FROM stagex/core-gmp@sha256:f90653ed07062074363542a77e26a2d16a142f9be5ebf6900b53f4ab8a82d39d AS gmp

FROM pallet-rust AS builder

COPY --from=pcsc-lite . /
COPY --from=nettle . /
COPY --from=gmp . /

ENV SOURCE_DATE_EPOCH=1
ENV CARGO_HOME=/usr/local/cargo

WORKDIR /build

COPY . .

ENV RUST_BACKTRACE=1
ENV TARGET_ARCH="x86_64-unknown-linux-musl"

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    find /usr/local/cargo/registry -name '.cargo-ok' -delete 2>/dev/null || true && \
    cargo fetch --locked --target $TARGET_ARCH

ARG EXTRA_RUSTFLAGS="-C codegen-units=1"
ARG CARGO_BUILD_FLAGS="--release"
ARG CARGO_PROFILE_DIR="release"

ENV RUSTFLAGS="${EXTRA_RUSTFLAGS} -C target-feature=+crt-static -C link-arg=-Wl,--build-id=none"
ENV NETTLE_STATIC=1

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,id=email-target,target=/build/target \
    --network=none \
    cargo build ${CARGO_BUILD_FLAGS} --frozen \
      --bin email-service \
      --target ${TARGET_ARCH} \
      && install -D -m 0755 /build/target/${TARGET_ARCH}/${CARGO_PROFILE_DIR}/email-service /usr/local/bin/email-service

FROM user-runtime AS runtime

COPY --from=gcc /usr/lib/libgcc_s.so.1 /usr/lib/
COPY --from=gcc /usr/lib/libstdc++.so.6 /usr/lib/
COPY --from=musl /lib/ld-musl-x86_64.so.1 /lib/
COPY --from=libunwind . /
COPY --from=ca-certificates /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/local/bin/email-service /usr/local/bin/email-service

WORKDIR /app

ENV RUST_LOG=info

EXPOSE 8082

ENTRYPOINT ["email-service"]
