FROM stagex/pallet-rust@sha256:9c38bf1066dd9ad1b6a6b584974dd798c2bf798985bf82e58024fbe0515592ca AS pallet-rust
FROM stagex/pallet-gcc-gnu-busybox@sha256:9f5f67721dacece876a5312d63fe727bbf176461cca73b77a531b3f1b96f8f66 AS gcc
FROM stagex/core-musl@sha256:d9af23284cca2e1002cd53159ada469dfe6d6791814e72d6163c7de18d4ae701 AS musl
FROM stagex/core-libunwind@sha256:eb66122d8fc543f5e2f335bb1616f8c3a471604383e2c0a9df4a8e278505d3bc AS libunwind
FROM stagex/core-ca-certificates@sha256:d135f1189e9b232eb7316626bf7858534c5540b2fc53dced80a4c9a95f26493e AS ca-certificates
FROM stagex/core-git@sha256:6b3e0055f6aeaa8465f207a871db2c63a939cd7406113e9d769ff3b37239f3d0 AS git
FROM stagex/core-zlib@sha256:06f5168e20d85d1eb1d19836cdf96addc069769b40f8f0f4a7a70b2f49fc18f8 AS zlib
FROM stagex/core-user-runtime@sha256:055ae534e1e01259449fb4e0226f035a7474674c7371a136298e8bdac65d90bb AS user-runtime
FROM stagex/user-docker-cli-buildx@sha256:e417fa8cc1665e51f4bf1c9f688e8b3b55097afdb1017f96642fd4ca73290519 AS docker-cli
FROM stagex/docker@sha256:d7e7202ce2b10b13571bd339a921030b0c53ecc4bd50ff8869f004913c4a08df AS docker-runtime
FROM stagex/user-pcsc-lite@sha256:2e0bb1cbeb9dd97be4e0594bd712dc138ee2710668281d3faa1a18d99a50979d AS pcsc-lite
FROM stagex/user-nettle@sha256:3b883ec8fb6781acff2517e7485d7e8f79f147f8fa2b3b644cb96da495af52e7 AS nettle
FROM stagex/core-gmp@sha256:35f1f6f285efd438e7d985dc0538b7a5ca1a228e69f50d39de2bcafe830b4beb AS gmp
FROM gcc AS gitconfig-builder
RUN mkdir -p /root && \
    echo '[safe]' > /root/.gitconfig && \
    echo '    directory = /git-repos/*' >> /root/.gitconfig

FROM pallet-rust AS builder

COPY --from=pcsc-lite . /
COPY --from=nettle . /
COPY --from=gmp . /

ENV SOURCE_DATE_EPOCH=1
ENV CARGO_HOME=/usr/local/cargo

WORKDIR /build

COPY . .

ENV RUST_BACKTRACE=1
ENV TARGET_ARCH="x86_64-unknown-linux-musl"

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    find /usr/local/cargo/registry -name '.cargo-ok' -delete 2>/dev/null || true && \
    cargo fetch --locked --target $TARGET_ARCH

ARG EXTRA_RUSTFLAGS="-C codegen-units=1"
ARG CARGO_BUILD_FLAGS="--release"
ARG CARGO_PROFILE_DIR="release"
ARG EXTRA_FEATURES=""

ENV RUSTFLAGS="${EXTRA_RUSTFLAGS} -C target-feature=+crt-static -C link-arg=-Wl,--build-id=none"
ENV NETTLE_STATIC=1

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,id=gateway-target,target=/build/target \
    --network=none \
    cargo build ${CARGO_BUILD_FLAGS} --frozen \
      --bin gateway \
      --target ${TARGET_ARCH} \
      ${EXTRA_FEATURES:+--features ${EXTRA_FEATURES}} \
      && install -D -m 0755 /build/target/${TARGET_ARCH}/${CARGO_PROFILE_DIR}/gateway /usr/local/bin/gateway

FROM scratch AS runtime
COPY --from=user-runtime . /
COPY --from=git . /
COPY --from=gcc . /
COPY --from=musl . /
COPY --from=libunwind . /
COPY --from=zlib . /
COPY --from=ca-certificates . /
COPY --from=builder /usr/local/bin/gateway /usr/local/bin/gateway
COPY --from=docker-runtime . /
COPY --from=docker-cli . /
COPY --from=gitconfig-builder /root/.gitconfig /root/.gitconfig

WORKDIR /app

EXPOSE 8000

ENTRYPOINT ["gateway"]
