FROM stagex/pallet-rust@sha256:abe9b95c93a5afa271f69fcd5eb18c8cd405fe5df6491a63c9418e3a170573dc AS pallet-rust
FROM stagex/pallet-gcc-gnu-busybox@sha256:67f4a035c680065fc0278517594ab07bf1b9416dc054508a8893ca20df04e415 AS gcc
FROM stagex/core-musl@sha256:42fd2ed18ac4d6336f08f1b6345e0bb7bc5570450a40e7255b6da79868bd2d6b AS musl
FROM stagex/core-libunwind@sha256:08cd9e229ef1b4f547c25436d06a2f893f252fc1c1d8b86affbaa91b0be05cef AS libunwind
FROM stagex/core-ca-certificates@sha256:8390dff73a4502614411e2b2ecb4e4e33b6cc10dc26cf2c6a46e5df71f4c4b03 AS ca-certificates
FROM stagex/core-git@sha256:ecd1de421f467072a76de5a38fce61dd0afb2ddd2c48d73c21effb5ad76342fb AS git
FROM stagex/core-zlib@sha256:5a21327b58c2ceeb3283a960540e19d9c35944961c68a7254e36056bf6f7d2d9 AS zlib
FROM stagex/core-user-runtime@sha256:1694accf42714684f8ebefed165dd202efb474d53cafbd47b63f93b47c999cad AS user-runtime
FROM stagex/user-docker-cli-buildx@sha256:74b6b0ccdea32074665ca145a37bee9631fddbcd8e9574296c753a6407787120 AS docker-cli
FROM stagex/docker@sha256:d7e7202ce2b10b13571bd339a921030b0c53ecc4bd50ff8869f004913c4a08df AS docker-runtime
FROM stagex/user-pcsc-lite@sha256:58e5846a6c0aa394d55f00a8bf743aab41e024449c31d199af868f012accc326 AS pcsc-lite
FROM stagex/user-nettle@sha256:110504b49f494b06121d1816eaa18aae2b772761e6748229d5bff1260a0f9860 AS nettle
FROM stagex/core-gmp@sha256:f90653ed07062074363542a77e26a2d16a142f9be5ebf6900b53f4ab8a82d39d AS gmp
FROM stagex/pallet-nodejs@sha256:5c96b25c18713976497a21c770057f2179c5014c5a025a02d2df9041d8f861f6 AS pallet-nodejs
FROM stagex/core-npm@sha256:fa8e48af8e76931eadb68acd610358363095eb393c607672570b15746d796a39 AS npm
FROM stagex/core-curl@sha256:fa58ff1a1c32677ce3034e69a2ee40081c799d6df68a7b1d5d480501de779030 AS curl
FROM stagex/core-busybox@sha256:e4a30addc8939c8e232472de904d1d9e97fc2e735fca9a9701ce49db04c6c181 AS busybox
FROM stagex/core-libzstd@sha256:bfe96f975a2a2a7a48aeb418b44accc79dd26d601a94d9f02b0562eaa0f89fdd AS libzstd
FROM gcc AS gitconfig-builder
RUN mkdir -p /root && \
    echo '[safe]' > /root/.gitconfig && \
    echo '    directory = /git-repos/*' >> /root/.gitconfig

FROM pallet-rust AS builder

COPY --from=pcsc-lite . /
COPY --from=nettle . /
COPY --from=gmp . /

ENV SOURCE_DATE_EPOCH=1
ENV CARGO_HOME=/usr/local/cargo

WORKDIR /build

COPY . .

ENV RUST_BACKTRACE=1
ENV TARGET_ARCH="x86_64-unknown-linux-musl"

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    find /usr/local/cargo/registry -name '.cargo-ok' -delete 2>/dev/null || true && \
    cargo fetch --locked --target $TARGET_ARCH

ARG EXTRA_RUSTFLAGS="-C codegen-units=1"
ARG CARGO_BUILD_FLAGS="--release"
ARG CARGO_PROFILE_DIR="release"
ARG EXTRA_FEATURES=""

ENV RUSTFLAGS="${EXTRA_RUSTFLAGS} -C target-feature=+crt-static -C link-arg=-Wl,--build-id=none"
ENV NETTLE_STATIC=1

RUN --mount=type=cache,target=/usr/local/cargo/registry \
    --mount=type=cache,target=/usr/local/cargo/git \
    --mount=type=cache,id=gateway-target,target=/build/target \
    --network=none \
    cargo build ${CARGO_BUILD_FLAGS} --frozen \
      --bin gateway \
      --target ${TARGET_ARCH} \
      ${EXTRA_FEATURES:+--features ${EXTRA_FEATURES}} \
      && install -D -m 0755 /build/target/${TARGET_ARCH}/${CARGO_PROFILE_DIR}/gateway /usr/local/bin/gateway

FROM pallet-nodejs AS frontend-deps

COPY --from=npm . /
COPY --from=git . /
COPY --from=busybox . /
COPY --from=curl . /
COPY --from=libzstd . /
COPY --from=gcc /usr/lib/libgcc_s.so.1 /usr/lib/libgcc_s.so.1

WORKDIR /app

COPY frontend/package.json frontend/package-lock.json* ./

RUN npm ci

FROM frontend-deps AS frontend-builder

ARG VITE_PADDLE_SANDBOX

ENV ENVIRONMENT=production
ENV NODE_ENV=production

COPY frontend/ ./

RUN VITE_PADDLE_SANDBOX="${VITE_PADDLE_SANDBOX}" /usr/bin/npm run build

FROM scratch AS runtime
COPY --from=user-runtime . /
COPY --from=git . /
COPY --from=gcc . /
COPY --from=musl . /
COPY --from=libunwind . /
COPY --from=zlib . /
COPY --from=ca-certificates . /
COPY --from=builder /usr/local/bin/gateway /usr/local/bin/gateway
COPY --from=docker-runtime . /
COPY --from=docker-cli . /
COPY --from=gitconfig-builder /root/.gitconfig /root/.gitconfig
COPY --from=frontend-builder /app/dist/ /app/frontend/

WORKDIR /app

EXPOSE 8000

ENTRYPOINT ["gateway"]
