run: /usr/bin/llama-server --host 0.0.0.0 --port 8083 -m /workdir/models/model.gguf --path /workdir/public --ctx-size 2048 -t 8
domain: chat.caution.dev
app_sources: https://codeberg.org/caution/demo-ai-inference.git 
memory_mb: 55000
cpus: 14 
nocache: true
e2e: true
